- src/components/Update/index.tsx
- src/utils/dayjs.ts
> fix: 正确的显示 app 更新时间

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/release.yml
- .github/workflows/sync-to-gitee.yml
- README.md
- index.html
- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
- src/constants/index.ts
> refactor: app 更名 EcoPaste

- src-tauri/tauri.conf.json
> chore: 更换 MacOS 安装包的样式

- src-tauri/src/tray.rs
- src-tauri/tauri.conf.json
> chore: 鼠标左键点击托盘图标将显示菜单，而不会打开应用窗口。

- src-tauri/src/plugins/fs_extra.rs
- src/constants/index.ts
- src/hooks/useTheme.ts
- src/pages/Settings/components/ThemeMode/index.tsx
- src/plugins/fsExtra.ts
- src/plugins/theme.ts
> fix: 修复主题模式为自动，但切换系统主题时无变化的问题

- src/components/ShortcutKey/index.tsx
- src/components/ShortcutKey/keys.ts
> feat: 适配 windows 和 linux 快捷键设置样式

- src/components/Update/index.tsx
- src/pages/Settings/index.tsx
- src/types/store.d.ts
> feat: 新增自动更新可配置项

- src-tauri/src/tray.rs
- src/App.tsx
- src/constants/index.ts
- src/layouts/Default/index.tsx
- src/pages/Settings/components/TrayClick/index.tsx
- src/pages/Settings/index.tsx
- src/stores/global.ts
- src/types/store.d.ts
> feat: windows 增加单击托盘配置项

- .vscode/settings.json
- package.json
- pnpm-lock.yaml
- src-tauri/tauri.conf.json
- src/App.tsx
- src/assets/css/global.scss
- src/components/Update/index.module.scss
- src/components/Update/index.tsx
- src/pages/Clipboard/History/components/List/components/Item/components/Text/index.module.scss
- src/pages/Clipboard/History/components/List/components/Item/components/Text/index.tsx
- src/pages/Clipboard/Settings/components/HistoryCapacity/index.tsx
- src/plugins/window.ts
- src/utils/is.ts
- tsconfig.json
> fix: 修复了点击 HTML 内容中的链接后直接在应用内显示目标网页的问题

- src/components/ShortcutKey/index.tsx
- src/hooks/useRegister.ts
- src/layouts/Default/index.tsx
> feat: 支持清除快捷键

- src/pages/Clipboard/History/components/List/components/Item/components/HTML/index.tsx
> fix: 修复 HTML 内容中固定定位元素导致的布局问题

- src/components/Scrollbar/index.tsx
- src/pages/Clipboard/History/components/Header/index.tsx
- src/pages/Clipboard/History/components/List/index.tsx
- src/pages/Clipboard/History/components/Search/index.tsx
- src/pages/Clipboard/History/index.tsx
- src/pages/Clipboard/Settings/components/DefaultFocus/index.tsx
- src/pages/Clipboard/Settings/components/SearchPosition/index.tsx
- src/pages/Clipboard/Settings/index.tsx
- src/plugins/window.ts
- src/stores/clipboard.ts
- src/types/store.d.ts
style: 优化剪切板中滚动条宽度 (#98)
feat: 支持配置搜索位置为顶部或底部 (#98)
feat: 支持配置默认聚焦项目为搜索框或列表首项 (#106)
closed #98 
closed #106
> feat: 支持配置搜索位置及默认聚焦项

- src/pages/Clipboard/History/components/List/index.tsx
- src/pages/Clipboard/History/index.tsx
> fix: 修复搜索后滚动位置异常的问题

- src/pages/Clipboard/History/index.tsx
- src/utils/is.ts
> fix: 去除 Windows 10 窗口的圆角效果，以避免阴影影响

- src/pages/Clipboard/History/components/List/index.tsx
> feat: 剪切板窗口支持快速回到顶部

- src/pages/Clipboard/History/components/List/components/Item/index.tsx
> perf: 当图片没有 OCR 内容时去掉右键菜单

- src/pages/Clipboard/History/components/List/components/Item/components/Text/index.module.scss
- src/pages/Clipboard/History/components/List/components/Item/components/Text/index.tsx
> fix: 修复滚动剪切板内容时一直闪烁的问题

- src-tauri/src/main.rs
- src/App.tsx
- src/router/index.ts
- src/types/router.d.ts
> fix: 修复点击部分链接直接在 app 内显示的问题

- package.json
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src-tauri/src/plugins/mod.rs
- src-tauri/src/plugins/paste.rs
- src-tauri/src/plugins/window.rs
- src/constants/index.ts
- src/pages/Clipboard/History/components/List/components/Item/index.tsx
- src/pages/Clipboard/Settings/components/DoubleClickFeedback/index.tsx
- src/plugins/clipboard.ts
- src/plugins/paste.ts
- src/types/store.d.ts
> feat: 实现回填剪切板内容的功能

- src/layouts/Preference/index.tsx
- src/locales/en-US.json
- src/locales/zh-CN.json
- src/pages/About/index.tsx
- src/pages/DataBackup/index.tsx
- refactor: 优化 关于页面 国际化
- feat: 偏好设置-数据备份 国际化
- fix: 偏好设置标题国际化
> feat: 偏好设置-数据备份 国际化

- src/pages/Clipboard/History/components/List/components/Item/index.tsx
> feat: 下载图片和导出文件将自动打开至目标目录

- src/locales/en-US.json
- src/locales/zh-CN.json
- src/pages/Clipboard/History/components/List/components/Item/index.tsx
- src/pages/Clipboard/Settings/index.tsx
- src/types/store.d.ts
> feat: 新增单击粘贴的配置项

- src/pages/Clipboard/History/components/List/components/Item/components/Header/index.tsx
- uno.config.ts
> feat: 点击复制的图标按钮后会出现短时间的成功图标

- src/locales/en-US.json
Hi there,
My apologies for the delay.
Here I am suggesting some minor improvements to translation based on common UI conventions
> chore: minor translation updates and consistency fixes

- .github/CONTRIBUTING.md
- .github/CONTRIBUTING.zh-CN.md
- README.md
- README.zh-CN.md
> docs: 英文版readme+contributing

- src/hooks/useFocus.ts
- src/pages/Clipboard/History/components/Header/index.tsx
- src/pages/Clipboard/History/components/List/components/Item/index.tsx
- src/pages/Clipboard/History/index.tsx
> refactor: 固定窗口自动粘贴时不隐藏窗口

- src-tauri/src/main.rs
- src-tauri/src/plugins/auto_launch.rs
- src-tauri/src/plugins/mod.rs
- src/constants/index.ts
- src/layouts/Preference/index.tsx
- src/pages/Clipboard/History/index.tsx
- src/plugins/autoLaunch.ts
- src/plugins/window.ts
> feat: 开机自动启动时不显示窗口

- src-tauri/src/core/tray.rs
- src-tauri/src/locales/en_us.rs
- src-tauri/src/locales/mod.rs
- src-tauri/src/locales/zh_cn.rs
- src-tauri/src/locales/zh_tw.rs
- src/constants/index.ts
- src/locales/index.ts
- src/locales/zh-TW.json
- src/pages/Settings/components/Language/index.tsx
- src/plugins/locale.ts
- src/utils/dayjs.ts
> feat: 加入繁体中文的翻译内容

- src/pages/Clipboard/History/index.tsx
- src/plugins/clipboard.ts
> fix: 修复 Windows 系统复制部分内容时一次性出现多条的问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
> fix: 修复 Windows 系统中复制的图像在部分 app 粘贴后颜色异常的问题

- src/pages/Clipboard/History/components/List/components/Item/components/HTML/index.tsx
- src/pages/Clipboard/History/components/List/components/Item/index.tsx
> feat: 剪切板 HTML 中的链接点击时需按 meta/ctrl 才跳转

- src/pages/Clipboard/History/index.tsx
- src/plugins/clipboard.ts
fix https://github.com/ayangweb/EcoPaste/issues/256
> fix: 复制相同内容增加防抖

- src/pages/Clipboard/History/components/Search/index.tsx
- src/pages/Clipboard/Settings/index.tsx
- src/stores/clipboard.ts
- src/types/store.d.ts
> feat: 加入自动清除搜索框内容配置项

- src-tauri/Cargo.toml
- src-tauri/src/core/app/mod.rs
- src-tauri/src/core/app/win.rs
- src-tauri/src/main.rs
- src-tauri/src/plugins/paste.rs
- src-tauri/src/plugins/window.rs
我提供一个思路，手头没有windows机器，你可以看下行不行，不行再说 哈哈哈
> fix: window窗口聚焦切换的问题

- src-tauri/src/main.rs
- src-tauri/src/plugins/paste.rs
- src-tauri/tauri.linux.conf.json
- **style: fix unused_variables warning**
- **feat: linux stub focus_previous_window**
- **chore: linux add rpm target**
> 修复 linux 编译错误，支持构建 rpm

- src/pages/Clipboard/History/components/Search/index.tsx
> feat: 支持 Ctrl/Meta + F 聚焦自定义搜索框

- src-tauri/tauri.linux.conf.json
如果编译失败可以尝试添加 `NO_STRIP=true`
```
NO_STRIP=true pnpm tauri build
```
> https://github.com/tauri-apps/tauri/issues/8929
> chore: linux 支持构建 AppImage

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/core/info.rs
- src-tauri/src/core/mod.rs
- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
支持使用命令行的方式获取当前系统/ app的信息，方便调试问题
支持参数 `--info` 或 `-i`
```bash
./EcoPaste.exe --info
```
> feat: 支持通过cli参数获取系统信息

- src-tauri/src/core/app/mod.rs
- src-tauri/src/core/tray.rs
- src-tauri/src/main.rs
- src-tauri/src/plugins/paste.rs
- src-tauri/src/plugins/window.rs
- src-tauri/tauri.conf.json
- src/layouts/Preference/index.tsx
- src/pages/Clipboard/History/index.tsx
- src/plugins/window.ts
- src/router/index.ts
> fix: 修复在 Windows 上 app 无限重启的 bug

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/core/tray.rs
- src-tauri/src/main.rs
> feat: 支持在退出前记住窗口的最后位置，重新启动时将恢复位置

- src/pages/Clipboard/Settings/index.tsx
- src/plugins/clipboard.ts
- src/stores/clipboard.ts
- src/types/store.d.ts
> feat: 支持富文本和 HTML 格式在复制时仅保留纯文本内容

- .github/workflows/multi-platform_build.yml
> chore: 多平台手动打包

- src-tauri/src/core/app/linux.rs
- src-tauri/src/plugins/paste.rs
- **refactor: 优化 linux 前台窗口监听**
- **refactor: linux 使用 Shift+Insert 粘贴**
> refactor: 优化 linux 自动粘贴

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/plugins/paste.rs
> feat: windows 用 shift + insert 模拟粘贴快捷键

- .github/workflows/multi-platform_build.yml
version 改了会有问题，也就 productName 能改了
> chroe: build 时 productName 追加日期

- src/pages/Clipboard/History/components/List/components/Item/index.tsx
> feat: 支持按下键盘上的删除键快捷删除条目

- src-tauri/tauri.conf.json
- src/pages/Clipboard/History/components/List/components/Item/components/Files/index.tsx
- src/pages/Clipboard/History/components/List/components/Item/components/Image/index.tsx
- src/pages/Clipboard/History/components/List/components/Item/index.tsx
- src/utils/is.ts
> feat: 支持单张图片文件的显示

- package.json
- pnpm-lock.yaml
- src/pages/Clipboard/History/components/List/components/Item/components/HTML/index.tsx
- src/pages/Clipboard/History/components/List/components/Item/components/RichText/index.tsx
- vite.config.ts
> feat: 正确的显示剪切板的富文本内容

- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/Clipboard/History/index.tsx
- src/pages/Clipboard/Settings/components/WindowPosition/index.tsx
- src/stores/clipboard.ts
- src/types/store.d.ts
> feat: 剪贴板窗口位置支持在多屏幕上显示

- src/plugins/clipboard.ts
> feat: 复制 excel 表格内容时忽略图片，存储文本内容

- src/pages/Clipboard/History/components/List/components/Item/components/Image/index.tsx
> feat: 支持剪切板图片内容完全显示

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src-tauri/src/plugins/macos_permissions.rs
- src-tauri/src/plugins/mod.rs
- src/App.tsx
- src/constants/index.ts
- src/layouts/Preference/index.tsx
- src/pages/General/components/MacosPermissions/index.tsx
- src/pages/General/index.tsx
- src/plugins/macosPermissions.ts
> feat: macos 新增权限设置配置项

- src-tauri/tauri.linux.conf.json
使用总入口的配置项：https://github.com/ayangweb/EcoPaste/blob/eeef2475bd52b86ef85bbba3b4adf5f4d26f258e/src-tauri/tauri.conf.json#L102
> chore: 修改 tauri 的配置文件

- src-tauri/src/plugins/clipboard.rs
- src/pages/Clipboard/History/components/List/components/Item/index.tsx
- src/plugins/clipboard.ts
> fix: 修复 windows 中富文本粘贴失败的问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
> feat: macOS 支持通过启动台或访达重新打开偏好设置窗口

- src/pages/Clipboard/Panel/components/List/index.tsx
- src/pages/Clipboard/Panel/components/Search/index.tsx
> feat: 支持无延迟实时搜索剪切板内容

- src-tauri/Cargo.lock
- src-tauri/src/main.rs
> fix: 修复了重启电脑后，窗口位置和大小丢失的问题

- src-tauri/src/plugins/tray.rs
- src/constants/index.ts
- src/layouts/Preference/index.tsx
- src/pages/Clipboard/Panel/components/Float/index.tsx
- src/pages/Clipboard/Panel/components/Search/index.tsx
- src/pages/Clipboard/Panel/index.tsx
- src/plugins/tray.ts
- src/plugins/window.ts
- src/types/plugin.d.ts
> fix: 修复 Windows 上点击托盘打开剪贴板窗口时，窗口位置配置未生效的问题

- src/pages/Clipboard/Panel/components/Search/index.tsx
> feat: 增强了纯键盘的操作体验

- src/components/ScrollRestore/index.tsx
- src/layouts/Preference/index.tsx
> fix: 修复了偏好设置窗口UI显示异常的问题

- src/pages/Clipboard/Panel/index.tsx
> fix: 修复了复制新内容时，分组归类错误的问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/core/setup/mac.rs
- src-tauri/src/core/setup/mod.rs
- src-tauri/src/plugins/window.rs
- src-tauri/tauri.conf.json
- src/constants/index.ts
- src/pages/Clipboard/Panel/index.tsx
- src/pages/General/index.tsx
- src/plugins/window.ts
- src/stores/global.ts
- src/types/store.d.ts
> feat: 新增`显示任务栏图标`配置项

- src/components/ProShortcut/index.tsx
- src/pages/Clipboard/Panel/components/List/components/Item/index.tsx
> feat: 支持单独将 `F1-F12` 键设置为快捷键使用

- src/layouts/Preference/index.tsx
- src/pages/Clipboard/Panel/components/List/index.tsx
- src/pages/Clipboard/Panel/components/Search/index.tsx
- src/pages/Clipboard/Panel/index.tsx
- src/pages/Clipboard/Settings/index.tsx
- src/stores/clipboard.ts
- src/types/store.d.ts
> feat: 新增 `回到顶部` 配置项

- src/pages/Clipboard/Panel/components/List/components/Item/components/Text/index.module.scss
- src/pages/Clipboard/Panel/components/List/components/Item/components/Text/index.tsx
- src/pages/Clipboard/Panel/components/List/components/Item/index.tsx
- src/pages/Clipboard/Panel/components/List/components/RemarkModel/index.tsx
- src/pages/Clipboard/Panel/components/List/index.tsx
> feat: 新增剪贴板内容备注功能

- src/pages/Clipboard/Panel/components/List/index.tsx
> feat: 支持按下 `home` 键回到顶部

- src-tauri/Cargo.lock
> fix: 修复了 Windows 打开右键菜单导致窗口未响应的问题

- src/pages/Clipboard/Panel/components/Float/index.tsx
> feat: linux 给剪贴板窗口添加边框

- src-tauri/capabilities/default.json
- src/database/index.tsx
- src/layouts/Preference/index.tsx
- src/pages/Clipboard/Panel/components/List/components/Item/index.tsx
- src/pages/Clipboard/Panel/components/List/index.tsx
- src/pages/Clipboard/Panel/components/Search/index.tsx
- src/pages/Clipboard/Panel/index.tsx
- src/pages/History/components/Delete/index.tsx
- src/types/database.d.ts
> feat: 支持搜索剪贴板内容的备注

- src-tauri/tauri.conf.json
- src-tauri/tauri.linux.conf.json
- src-tauri/tauri.windows.conf.json
- src/components/Tray/index.tsx
> fix: 修复 macOS 无法显示本地路径中以 `.` 开头的文件夹中图片的问题

- src-tauri/capabilities/default.json
- src-tauri/tauri.conf.json
- src/constants/index.ts
- src/layouts/Preference/index.tsx
- src/pages/About/components/Thank/index.tsx
- src/pages/About/index.tsx
- src/pages/Clipboard/Panel/index.tsx
- src/plugins/backup.ts
- src/utils/path.ts
> fix: 修复部分 windows 电脑丢失配置项的问题

- src/constants/index.ts
- src/pages/Clipboard/Panel/index.tsx
- src/plugins/window.ts
> fix: 修复 linux 打开窗口在左上角的问题

- Cargo.lock
- Cargo.toml
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/core/setup/mod.rs
- src-tauri/src/lib.rs
- src-tauri/src/plugins/autostart/Cargo.toml
- src-tauri/src/plugins/autostart/build.rs
- src-tauri/src/plugins/autostart/permissions/default.toml
- src-tauri/src/plugins/autostart/src/commands.rs
- src-tauri/src/plugins/autostart/src/lib.rs
- src/constants/index.ts
- src/layouts/Preference/index.tsx
- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/General/index.tsx
- src/plugins/autostart.ts
- src/stores/global.ts
- src/types/store.d.ts
> feat: 新增 `通用设置 > 应用设置 > 静默启动` 配置项

- src-tauri/src/plugins/backup/src/commands.rs
- src-tauri/src/plugins/fs-extra/src/commands.rs
- src/plugins/clipboard.ts
- src/types/plugin.d.ts
> fix: 修复 Linux 导出数据报错的问题

- src/plugins/backup.ts
> fix: 修复了 Windows 导出数据报错的问题

- Cargo.lock
- Cargo.toml
> fix: 修复 MacOS 搜索闪退的问题

- Cargo.lock
- Cargo.toml
- src-tauri/Cargo.toml
- src-tauri/src/core/setup/mac.rs
- src-tauri/src/lib.rs
- src-tauri/src/plugins/paste/Cargo.toml
- src-tauri/src/plugins/paste/src/commands/mac.rs
- src-tauri/src/plugins/window/Cargo.toml
- src-tauri/src/plugins/window/src/commands.rs
- src/constants/index.ts
- src/hooks/useFocus.ts
> feat: 支持在 MacOS 上打开剪贴板窗口时不抢占其他窗口的焦点

- src-tauri/src/core/setup/mac.rs
> fix: 修复剪贴板窗口无法显示在 macOS 全屏应用上的问题

- src-tauri/capabilities/default.json
> fix: 修复了双击空白处窗口会放大的问题

- src-tauri/tauri.windows.conf.json
fixed #723
参考：https://tauri.app/reference/config/#nsisinstallermode
> feat: windows 安装程序支持以管理员权限运行，避免安装失败

- src-tauri/src/core/setup/mac.rs
> fix: 修复在 macOS 搜索时系统输入法被覆盖的问题

- src/pages/Clipboard/Panel/index.tsx
- src/pages/Clipboard/Settings/index.tsx
> fix: 开放Linux下的复制音效功能，经测试正常！

- src-tauri/src/plugins/backup/src/commands.rs
- src/utils/path.ts
> feat: 开发环境和生产环境的配置文件区分

- src/components/Scrollbar/index.tsx
- src/pages/Clipboard/Panel/components/List/index.tsx
> fix: 修复了剪贴板窗口无法用鼠标选中滚动条的问题

- src/pages/Clipboard/Panel/components/List/components/NoteModal/index.tsx
> fix: 修复了 Windows 备注时出现“保存的数据”的问题

- src-tauri/tauri.conf.json
- src-tauri/tauri.macos.conf.json
- src/constants/index.ts
- src/pages/Clipboard/Panel/components/List/components/Item/index.tsx
- src/pages/Clipboard/Panel/components/List/index.tsx
> feat: 支持 Ctrl/Command + D 收藏或取消收藏剪贴板内容

- src/pages/Clipboard/Panel/components/List/components/Item/components/Header/index.tsx
- src/pages/Clipboard/Panel/components/List/components/Item/index.tsx
> feat: 将剪贴板内容的“复制”图标按钮替换为“粘贴为纯文本”图标按钮

- .github/LINUX_AUR/preview/PKGBUILD
- .github/LINUX_AUR/release/PKGBUILD
> fix: #587 修复AUR安装后，图标不显示问题

- package.json
- pnpm-lock.yaml
- src/utils/is.ts
> fix: 修复纯文本被误识别为颜色的问题

- src/App.tsx
- src/utils/store.ts
> fix: 修复更新后托盘仍然显示旧版本号的问题

- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/Backup/components/Manual/index.tsx
> feat: 在导入或导出前弹出确认提示框

- src/components/Tray/index.tsx
- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
> feat: 支持从托盘菜单中重启应用

- src/hooks/useWindowState.ts
> fix: 修复部分 Windows 无法打开偏好设置窗口的问题

- src/plugins/clipboard.ts
> feat: 过滤掉长度为 0 的字符串

- src/pages/Clipboard/Panel/components/Dock/index.tsx
- src/plugins/window.ts
- src/utils/monitor.ts
> fix: 修复 macOS 多显示器下剪贴板窗口位置异常的问题

- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/Clipboard/Panel/components/List/components/NoteModal/index.tsx
- src/pages/Clipboard/Settings/index.tsx
- src/stores/clipboard.ts
- src/types/store.d.ts
> feat: 新增 `剪贴板 > 内容设置 > 自动收藏` 配置项

- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/Clipboard/Panel/components/List/components/Item/index.tsx
- src/pages/Clipboard/Panel/components/List/index.tsx
- src/pages/Clipboard/Settings/index.tsx
- src/stores/clipboard.ts
- src/types/store.d.ts
> feat: 新增 `剪贴板 > 内容设置 > 删除确认` 配置项

- src/components/UpdateApp/index.tsx
- src/hooks/useImmediate.ts
- src/layouts/Preference/index.tsx
- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/History/components/Duration/index.tsx
- src/pages/History/components/MaxCount/index.tsx
- src/pages/History/index.tsx
- src/stores/clipboard.ts
- src/types/shared.d.ts
- src/types/store.d.ts
- src/utils/store.ts
> feat: 新增 `历史记录 > 最大保留条数` 配置项

- src/database/index.tsx
- src/pages/Backup/components/Manual/index.tsx
- src/pages/Backup/components/SavePath/index.tsx
- src/utils/shared.ts
> fix: 修复 Windows 无法修改数据存储路径的问题

- src/pages/Clipboard/Panel/components/List/components/Item/components/Files/components/File/index.tsx
- src/utils/store.ts
> fix: 修复因数据存储目录不存在导致应用无法正常使用的问题

- biome.json
- src/pages/Backup/components/SavePath/index.tsx
- src/pages/Clipboard/Panel/components/List/components/Item/components/HTML/index.tsx
> fix: 修复了复制媒体后的自动播放问题

- package.json
- pnpm-lock.yaml
- src/assets/css/global.scss
- src/components/ProShortcut/index.tsx
- src/components/ProShortcut/keys.ts
- src/hooks/useOSKeyPress.ts
- src/hooks/useTauriFocus.ts
- src/hooks/useTray.ts
- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/Main/components/Float/index.tsx
- src/pages/Main/components/List/components/Item/components/Files/components/File/index.tsx
- src/pages/Main/components/List/components/Item/index.tsx
- src/pages/Preference/components/Clipboard/index.tsx
- src/pages/Preference/components/General/components/MacosPermissions/index.tsx
- src/pages/Preference/components/Shortcut/components/Preset/index.tsx
- src/pages/Preference/components/Shortcut/components/QuickPaste/index.tsx
- src/pages/Preference/components/Shortcut/index.tsx
- src/pages/Preference/index.tsx
- src/plugins/clipboard.ts
- src/plugins/window.ts
- src/utils/is.ts
> feat: 预设快捷键可在「偏好设置 > 快捷键」中查看

- src/components/ProShortcut/keys.ts
- src/locales/en-US.json
- src/locales/ja-JP.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
- src/pages/Main/components/Group/index.tsx
- src/pages/Main/components/Pin/index.tsx
- src/pages/Preference/components/Shortcut/components/Preset/index.tsx
> feat: 支持通过快捷键固定剪贴板窗口
